apiVersion: apps/v1

kind: Deployment

metadata:
  name: livenessprobe-deployment
  labels:
    app: livenessprobeapp

spec:
  template:
    metadata:
      name: livenessprobe-pod
      labels:
        app: livenessprobeapp

    spec:
      containers:
        - name: busybox-container
          image: busybox
          args:
            - /bin/sh
            - -c
            - touch hello; sleep 20; rm -f hello; sleep 600;
          livenessProbe:
            exec:
              command:
                - cat
                - hello
            periodSeconds: 3
            initialDelaySeconds: 5

  replicas: 1
  selector:
    matchLabels:
      app: livenessprobeapp
